### ISSUE TITLE
Add better error messages for missing data

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#41]
In 14_cnn, there is some computation that does not benefit from having a GPU, which could be pre-computed on a machine without a GPU and saved. So when running on a machine with GPU, fewer imports are needed (and hence less headache installing this machine/talking to the admins).

Same probably goes for 15_cnn_test.

**Comment by MatthewJA** [comment]
I'm going to make a standalone script that trains a CNN. There is some computation that doesn't need the GPU (snipping images, basically) and I'll try and isolate that as much as possible, but I don't know what the trade-off will be between time and disk space.

**Comment by MatthewJA** [comment]
Done. 89efb5652292456fc34e5389629fe84993e8d5c3

**Comment by chengsoonong** [comment]
I think some more informative error messages about missing files would be good.

mreid-thunderbolt:crowdastro cong$ ls training.h5 
training.h5
mreid-thunderbolt:crowdastro cong$ ls data/
ATLASDR3_cmpcat_23July2015.dat      radio_groups.json
cdfs                    radio_subjects.json
elais                   sanitized_radio_2016-03-01.tar.gz
radio_classifications.json
mreid-thunderbolt:crowdastro cong$ ls data/cdfs/
2x2             cdfs_11JAN2014_2x2_5x5.tgz
5x5
mreid-thunderbolt:crowdastro cong$ ls data/elais/
2x2             elais_11JAN2014_2x2_5x5.tgz
5x5
mreid-thunderbolt:crowdastro cong$ python crowdastro/preprocess_cnn_images.py training.h5 data
Traceback (most recent call last):
  File "crowdastro/preprocess_cnn_images.py", line 81, in <module>
    preprocess(args.data, args.images)
  File "crowdastro/preprocess_cnn_images.py", line 50, in preprocess
    sources = hf['data']['source']
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (-------src-dir--------/h5py/_objects.c:2582)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (-------src-dir--------/h5py/_objects.c:2541)
  File "/Users/cong/anaconda3/lib/python3.4/site-packages/h5py/_hl/group.py", line 166, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (-------src-dir--------/h5py/_objects.c:2582)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (-------src-dir--------/h5py/_objects.c:2541)
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (-------src-dir--------/h5py/h5o.c:3551)
KeyError: "Unable to open object (Object 'source' doesn't exist)"

**Comment by MatthewJA** [comment]
There's a few issues along the lines of "clean up the package" &mdash; I'll mark them "help wanted" for now and fix them up after my thesis if I have time.
