### ISSUE TITLE
document crowdastro

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#43]
Add to README.md

**Comment by chengsoonong** [comment]
mreid-thunderbolt:crowdastro cong$ python -m crowdastro training_data processed.db consensuses gator_cache training.h5 --atlas
Using TensorFlow backend.
Traceback (most recent call last):0.04%)
  File "/Users/cong/anaconda3/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/cong/anaconda3/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/cong/Repo/crowdastro/crowdastro/__main__.py", line 98, in <module>
    sys.exit(main())
  File "/Users/cong/Repo/crowdastro/crowdastro/**main**.py", line 95, in main
    args.func(args)
  File "/Users/cong/Repo/crowdastro/crowdastro/**main**.py", line 23, in training_data
    atlas=args.atlas)
  File "/Users/cong/Repo/crowdastro/crowdastro/training_data.py", line 48, in generate
    [str(subject['_id'])])
sqlite3.OperationalError: no such column: subject_id

**Comment by MatthewJA** [comment]
Ah, this is a different issue. I just need to update the training data code to match the new API - will do soon.

**Comment by chengsoonong** [comment]
Moved to new issue #44
