### ISSUE TITLE
update the training data code to match the new API

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#44]

**Comment by chengsoonong** [comment]
Still broken.

$ python -m crowdastro training_data processed.db consensuses gator_cache training.h5 --atlas

Using TensorFlow backend.
Traceback (most recent call last):0.04%)
  File "/Users/cong/anaconda3/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/cong/anaconda3/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/cong/Repo/crowdastro/crowdastro/__main__.py", line 98, in <module>
    sys.exit(main())
  File "/Users/cong/Repo/crowdastro/crowdastro/**main**.py", line 95, in main
    args.func(args)
  File "/Users/cong/Repo/crowdastro/crowdastro/**main**.py", line 23, in training_data
    atlas=args.atlas)
  File "/Users/cong/Repo/crowdastro/crowdastro/training_data.py", line 48, in generate
    [str(subject['_id'])])
sqlite3.OperationalError: no such column: subject_id

**Comment by MatthewJA** [comment]
> `File "/Users/cong/Repo/crowdastro/crowdastro/training_data.py", line 48, in generate
> [str(subject['_id'])])`

[This line](https://github.com/chengsoonong/crowdastro/blob/6f5e4bd010d6bf8fee575070af8577221c39b02b/crowdastro/training_data.py#L48) doesn't match the traceback - did you pull?

**Comment by chengsoonong** [comment]
My bad. Running now.
