### ISSUE TITLE
update README, requirements, and data dependencies

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#89]
The train_lr and test_lr interface has obviously changed. If possible do not use sknn. Even after installing that

$ python3 -m crowdastro.train
Traceback (most recent call last):
  File "/Users/ong017/anaconda3/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/ong017/anaconda3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/ong017/Repo/crowdastro/crowdastro/train.py", line 22, in <module>
    import unbalanced_dataset.over_sampling.random_over_sampler as ros
ImportError: No module named 'unbalanced_dataset'

**Comment by MatthewJA** [comment]
Given that the neural network did pretty terribly, I can probably remove both of these dependencies.

**Comment by chengsoonong** [comment]
Please do.

Also write a paragraph in the README about the aims of the project.
